/**
 * 前端路由配置文件，只有需要添加前端路由可在此文件里添加。
 * 格式：{
 *     name:'',
 *     routes:[
 *         {
 *             name:'',
 *             route:''
 *         },
 *          ...
 *     ]
 * }
 * Author: Wei Liu
 * Date: 2021/07/29
 */
export default [
    {
        name:'人文学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/ch/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/ch/en'
            }
        ]
    },
    {
        name:'外国语言文化与国际交流学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/sis/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/sis/en'
            }
        ]
    },
    {
        name:'传媒与国际文化学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cmic/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cmic/en'
            }
        ]
    },
    {
        name:'艺术与考古学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/soaa/zh'
            }
        ]
    },
    {
        name:'经济学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cec/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cec/en'
            }
        ]
    },
    {
        name:'光华法学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/ghls/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/ghls/en'
            }
        ]
    },
    {
        name:'教育学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/ced/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/ced/en'
            }
        ]
    },
    {
        name:'管理学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/som/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/som/en'
            }
        ]
    },
    {
        name:'公共管理学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/spa/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/spa/en'
            }
        ]
    },
    {
        name:'马克思主义学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/marx/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/marx/en'
            }
        ]
    },
    {
        name:'数学科学学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/math/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/math/en'
            }
        ]
    },
    {
        name:'物理学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/physics/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/physics/en'
            }
        ]
    },
    {
        name:'化学学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/chem/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/chem/en'
            }
        ]
    },
    {
        name:'地球科学学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/gs/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/gs/en'
            }
        ]
    },
    {
        name:'心理与行为科学学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/psych/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/psych/en'
            }
        ]
    },
    {
        name:'机械工程学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/me/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/me/en'
            }
        ]
    },
    {
        name:'材料科学与工程学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/mse/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/mse/en'
            }
        ]
    },
    {
        name:'能源工程学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/doe/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/doe/en'
            }
        ]
    },
    {
        name:'电气工程学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/ee/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/ee/en'
            }
        ]
    },
    {
        name:'建筑工程学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/ccea/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/ccea/en'
            }
        ]
    },
    {
        name:'化学工程与生物工程学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/che/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/che/en'
            }
        ]
    },
    {
        name:'海洋学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/oc/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/oc/en'
            }
        ]
    },
    {
        name:'航空航天学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/saa/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/saa/en'
            }
        ]
    },
    {
        name:'高分子科学与工程学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/polymer/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/polymer/en'
            }
        ]
    },
    {
        name:'光电科学与工程学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/opt/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/opt/en'
            }
        ]
    },
    {
        name:'信息与电子工程学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/isee/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/isee/en'
            }
        ]
    },
    {
        name:'控制科学与工程学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cse/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cse/en'
            }
        ]
    },
    {
        name:'计算机科学与技术学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cs/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cs/en'
            }
        ]
    },
    {
        name:'软件学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cst/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cst/en'
            }
        ]
    },
    {
        name:'生物医学工程与仪器科学学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cbeis/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cbeis/en'
            }
        ]
    },
    {
        name:'生命科学学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cls/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cls/en'
            }
        ]
    },
    {
        name:'生物系统工程与食品科学学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/caefs/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/caefs/en'
            }
        ]
    },
    {
        name:'环境与资源学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cers/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cers/en'
            }
        ]
    },
    {
        name:'农业与生物技术学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cab/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cab/en'
            }
        ]
    },
    {
        name:'动物科学学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cas/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cas/en'
            }
        ]
    },
    {
        name:'医学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cmm/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cmm/en'
            }
        ]
    },
    {
        name:'药学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/cps/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/cps/en'
            }
        ]
    },
    {
        name:'医学院附属第一医院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/zy91/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/zy91/en'
            }
        ]
    },
    {
        name:'医学院附属第二医院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/z2hospital/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/z2hospital/en'
            }
        ]
    },
    {
        name:'医学院附属邵逸夫医院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/srrsh/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/srrsh/en'
            }
        ]
    },
    {
        name:'医学院附属妇产科医院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/womanhospital/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/womanhospital/en'
            }
        ]
    },
    {
        name:'医学院附属儿童医院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/zjuch/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/zjuch/en'
            }
        ]
    },{
        name:'医学院附属口腔医院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/zjuss/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/zjuss/en'
            }
        ]
    },
    {
        name:'医学院附属第四医院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/zju4h/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/zju4h/en'
            }
        ]
    },
    {
        name:'国际联合学院（海宁国际校区）',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/intl/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/intl/en'
            }
        ]
    },
    {
        name:'浙江大学爱丁堡大学联合学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/zje/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/zje/en'
            }
        ]
    },
    {
        name:'浙江大学伊利诺伊大学厄巴纳香槟校区联合学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/zjui/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/zjui/en'
            }
        ]
    },
    {
        name:'浙江大学国际联合商学院',
        routes:[
            {
                name:'中文网',
                route:'/index/newsList/zibs/zh'
            },
            {
                name:'英文网',
                route:'/index/newsList/zibs/en'
            }
        ]
    }
]